### ISSUE TITLE
Slider doesn't update properly in all cases

### ISSUE THREAD

**Issue by spencerwahl** [RAMP-PCAR/dqvue#22]
Testing using CIP
- Move slider to 20 year
- select (on chart) a subsection of those 20 years, towards the left
- Chart view moves but slider stays the same

**Comment by AleksueiR** [comment]
Here's what is happening:

- select (on chart) a subsection of those 20 years, towards the left
  - chart fires a `setExtremes` with total number of year fewer than 20 (say 1904, 1908)
  - chart starts zoom in animation ([`minRange`](https://api.highcharts.com/highcharts/xAxis.minRange) options refers to the minimum range displayed on the chart, but instead of starting with the min value and adding the min range after it, Highcharts pad the selected range on both sides up-to the `minimumRange` value)
  - dqv tries to set the slider to the supplied extremes
  - slider updates but respects the 20 year limit and fires its update event with new extremes (say 1904, 1924)
  - dqv now tries to set the chart to new extremes (say 1904, 1924)
  - chart just started animating the initial `setExtremes`, and ignores the second call

Jsfiddle: http://jsfiddle.net/k00s0uzh/14/

Adding a timeout before calling `setExtremes` seems to help, but I hate if we have to do that.
