### ISSUE TITLE
specific series events override plotOptions series events

### ISSUE THREAD

**Issue by spencerwahl** [RAMP-PCAR/dqvue#25]
```
        plotOptions: {
            series: {
                events: {
                    hide: function () {
                        $('#chart-table-label').html('Empty table');
                    },
                    show: () => {
                        $('#chart-table-label').html('');
                    }
                }
            }
        },
        series: [
            {
                events: {
                    hide: function () {
                        console.log('a');
                    },
                    show: () => {
                        console.log('b');
                    }
                }
            }
        ]
```

The 2 console log events will fire but not the jQuery calls.

**Comment by AleksueiR** [comment]
Opened a Highcharts issue (https://github.com/highcharts/highcharts/issues/7914) to check if this behaviour is intended.

**Comment by AleksueiR** [comment]
Yeap, this is intended behaviour.

Wrapping series `show/hide` and other events doesn't seem practical on the DQV side anymore since overriding `series.events` will kill any user-defined handlers on the `plotOptions.series.events`; and wrapping `plotOptions.series.events` might be killed by the user-defined `series.events` handlers.

Wrapping `xAxis.events.setExtremes` seems to be safe, since this handler is not being overridden by anything.  

I suggest we rollback this change: https://github.com/RAMP-PCAR/dqvue/pull/23. This logic for updating the table on series toggle will have to be implemented on the host page, as we cannot safely wrap Highcharts events to achieve that.

It's highly unlikely Highcharts will implement event bubbling.

**Comment by spencerwahl** [comment]
We should also add an endpoint to trigger a table redraw so that implementing this on the host page is much simpler. When the table is redrawn it will only draw with the data of visible series.
